workflows:
  android-app:
    name: Quotes Trivia
    environment:
      vars:
        SONAR_TOKEN: Encrypted(Z0FBQUFBQmhDVnJpRG5DekJNZGIwVmhFT2I4Qlk0TkZmVmJERE9mbVVUaDh4My1GNV9WTWlKd3ZzX3E5TUxZeWJYcEd6NEt3ell2RldaWEYycDZZZTVUOWJCTkxqNTk3NmZyamloV0d2Y2ZXZUszRmZlYTF3MERWcEdSZGRhRXFvVUFSUE4zTUN3bmU=) # enter the encrypted version of your SonarCloud token
        SONAR_HOST_URL: https://chvd.eu.ngrok.io
       
    scripts:    
      - |
        # Generate and upload code analysis report
        ./android/gradlew sonarqube -Dsonar.projectKey=ChrisReferenceProjects_FlutterWhatsAppClone -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN   


