workflows:
  android-app:
    name: Quotes Trivia
    environment:
      vars:
        SONAR_TOKEN: Encrypted(Z0FBQUFBQmhDVnJpRG5DekJNZGIwVmhFT2I4Qlk0TkZmVmJERE9mbVVUaDh4My1GNV9WTWlKd3ZzX3E5TUxZeWJYcEd6NEt3ell2RldaWEYycDZZZTVUOWJCTkxqNTk3NmZyamloV0d2Y2ZXZUszRmZlYTF3MERWcEdSZGRhRXFvVUFSUE4zTUN3bmU=) # enter the encrypted version of your SonarCloud token
        SONAR_HOST_URL: https://chvd.eu.ngrok.io
       
    scripts:
      - |
        # Generate debug build
        ./android/gradlew assembleDebug        
      - |
        # Generate and upload code analysis report
        ./android/gradlew sonarqube \
          -Dsonar.projectKey=ChrisReferenceProjects_FlutterWhatsAppClone \
          -Dsonar.host.url=https://chvd.eu.ngrok.io \
          -Dsonar.login=4516e6638e29cb6d87a33a9302d2d33fd5dcd891     
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - christophe.havard@hotmail.fr # enter your email
